
services:
  db:
    image: postgres:16
    container_name: devops_db
    restart: always
    environment:
      POSTGRES_DB: devopslab
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops -d devopslab"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: devops_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://devops:devops@db:5432/devopslab
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    container_name: devops_prometheus
    restart: always
    depends_on:
      - api
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: devops_grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro

volumes:
  postgres_data:
  grafana_data:
